const accent = "#FF4D6A";
const accentSoft = "#FF7A92";
const accentLight = "#FFE5EA";

export default {
  light: {
    text: "#0D0D0D",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    background: "#FAFAFA",
    backgroundSecondary: "#F3F4F6",
    backgroundCard: "#FFFFFF",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
    tint: accent,
    tintSoft: accentSoft,
    tintLight: accentLight,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: accent,
    success: "#10B981",
    successLight: "#D1FAE5",
    warning: "#F59E0B",
    warningLight: "#FEF3C7",
    overlay: "rgba(0,0,0,0.5)",
    gradient: ["#FF4D6A", "#FF8C69"] as [string, string],
    gradientCard: ["#FFFFFF", "#FFF5F7"] as [string, string],
    verified: "#3B82F6",
    verifiedLight: "#EFF6FF",
    shadowColor: "#000",
  },
  dark: {
    text: "#F9FAFB",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    background: "#0A0A0A",
    backgroundSecondary: "#1A1A1A",
    backgroundCard: "#141414",
    border: "#2A2A2A",
    borderLight: "#1E1E1E",
    tint: accent,
    tintSoft: accentSoft,
    tintLight: "#3D1219",
    tabIconDefault: "#6B7280",
    tabIconSelected: accent,
    success: "#10B981",
    successLight: "#064E3B",
    warning: "#F59E0B",
    warningLight: "#78350F",
    overlay: "rgba(0,0,0,0.7)",
    gradient: ["#FF4D6A", "#FF8C69"] as [string, string],
    gradientCard: ["#141414", "#1A0D10"] as [string, string],
    verified: "#60A5FA",
    verifiedLight: "#1E3A5F",
    shadowColor: "#000",
  },
};
